language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t priyancapillay/react-test -f ./client/Dev.Dockerfile ./client

script:
  - docker run -e CI=true priyancapillay/react-test npm test

after_success:
  - docker build -t priyancapillay/multi-client ./client
  - docker build -t priyancapillay/multi-nginx ./nginx
  - docker build -t priyancapillay/multi-server ./server
  - docker build -t priyancapillay/multi-worker ./worker

#Login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#Take those images and push them to docker hub
  - docker push priyancapillay/multi-client
  - docker push priyancapillay/multi-nginx
  - docker push priyancapillay/multi-server
  - docker push priyancapillay/multi-worker